name: CI
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gatsby Publish
        env:
          DATO_ACCESS_TOKEN: ${{ secrets.DATO_ACCESS_TOKEN }}
        uses: enriikke/gatsby-gh-pages-action@v2.1.2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: public
